name: Build native-image

on:
  # manual trigger build
  workflow_dispatch:

jobs:
  build-jar:
    name: 'Build JAR package'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v2

      - name: 'Set up Java'
        uses: actions/setup-java@v2
        with:
          # Eclipse Temurin
          distribution: 'temurin'
          java-version: '11'
          architecture: x64
          # use most up-to-date version of Java
          check-latest: true
          # use built-in package manager for caching and restoring dependencies
          cache: 'maven'

      - name: 'Build with Maven'
        run: 'mvn'
        
      - name: Temporarily save package
        uses: actions/upload-artifact@v2
        with:
          name: java-binary
          path: |
            ${{ github.workspace }}/example-app/target/*.jar
  
  build-native-image:
    name: 'Build with GraalVM Native Image on ${{ matrix.os }}'
    needs: [ build-jar ]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            artifact_name: macos-binary
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v2
        
      - name: Download application package
        uses: actions/download-artifact@v2
        with:
          name: java-binary
      
      - uses: graalvm/setup-graalvm@v1
        with:
          version: '22.0.0.2'
          java-version: '11'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: 'Build native image on macOS'
        run: mvn -P native package
        if: runner.os == 'macOS'
      
      - name: Temporarily save package
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.artifact_name }}
          path: |
            ${{ github.workspace }}/example-app/target/NativeImageUsingJPMS-App
  
  publish-binaries:
    name: 'Publish binaries to GitHub packages'
    needs: [ build-native-image ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - artifact_name: java-binary
            binary_name: nubesgen-cli-*.jar
            file_glob: true
          - artifact_name: linux-binary
            binary_name: NativeImageUsingJPMS-linux
            file_glob: false
          - artifact_name: macos-binary
            binary_name: NativeImageUsingJPMS-osx
            file_glob: false
          - artifact_name: windows-binary
            binary_name: NativeImageUsingJPMS-windows.exe
            file_glob: false
    steps:
      - name: Download binary
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.artifact_name }}
          
      - name: Upload binary to the GitHub release page
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.binary_name }}
          file_glob: ${{ matrix.file_glob }}
          tag: ${{ github.ref }}
          overwrite: true

